edition: 1.0.0
name: web-framework-app
access: "default"

vars:
  region: "cn-hangzhou"
  service:
    name: "strapi"
    description: 'Serverless Devs Web Framework Service'
    nasConfig: auto

services:
  strapi-image-production:
    component: fc
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: strapi-image-production
        description: 'Serverless Devs Web Framework Function'
        runtime: custom-container
        timeout: 60
        caPort: 1337
        cpu: 1
        diskSize: 512
        memorySize: 2048
        environmentVariables:
          NODE_ENV: production
          PATH: /opt:/opt/nodejs16/bin:/usr/local/bin/apache-maven/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ruby/bin
          API_TOKEN_SALT: ${env.API_TOKEN_SALT}
          DATABASE_FILENAME: /mnt/auto/strapi/data.db
          PORT: '1337'
          APP_KEYS: ${env.APP_KEYS}
          JWT_SECRET: ${env.JWT_SECRET}
          ADMIN_JWT_SECRET: ${env.ADMIN_JWT_SECRET}
          HOST: 0.0.0.0
          DATABASE_CLIENT: sqlite
          TRANSFER_TOKEN_SALT: ${env.TRANSFER_TOKEN_SALT}
        customContainerConfig:
          image: registry.cn-hangzhou.aliyuncs.com/aliwarefed/start-strapi:v3
          accelerationType: 'Default'
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: '/*'
              methods:
                - GET
                - POST
                - PUT
                - DELETE
